language: rust
matrix:
  include:
  - rust: stable
    install: cd rust/berg-compiler && cargo build --no-default-features --verbose
    script: cd rust/berg-compiler && cargo build --no-default-features --verbose && cargo test --verbose
  - rust: beta
    install: cd rust/berg-compiler && cargo build --no-default-features --verbose
    script: cd rust/berg-compiler && cargo build --no-default-features --verbose && cargo test --verbose
  - rust: nightly
    install: cd rust/berg-compiler && cargo build --verbose
    script: cd rust/berg-compiler && cargo build --verbose && cargo test --verbose
  allow_failures:
    - rust: nightly
