language: rust
language: rust

before_install: cd rust/berg-compiler
install: cargo build $CARGO_BUILD_FLAGS --verbose
script: cargo build $CARGO_BUILD_FLAGS --verbose && cargo test --verbose

matrix:
  include:
  - rust: stable
    env: { CARGO_BUILD_FLAGS: --no-default-features }
  - rust: beta
    env: { CARGO_BUILD_FLAGS: --no-default-features }
  - rust: nightly
  allow_failures:
    - rust: nightly
