#[macro_use]
pub mod compiler_test;

compiler_tests! {
    add0_0: "0+0" => type(0),
    add0_1: "0+1" => type(1),
    add1_0: "1+0" => type(1),
    add1_1: "1+1" => type(2),
    add123_123: "123+123" => type(246),
    add1_2_3: "1+2+3" => type(6),

    sub0_0: "0-0" => type(0),
    sub1_1: "1-1" => type(0),
    sub2_1: "2-1" => type(1),
    sub1_2: "1-2" => type(-1),
    sub1_0: "1-0" => type(1),
    sub369_123: "369-123" => type(246),
    sub6_2_1: "6-2-1" => type(3),

    mul0_0: "0*0" => type(0),
    mul0_1: "0*1" => type(0),
    mul1_0: "1*0" => type(0),
    mul1_1: "1*1" => type(1),
    mul11_11: "11*11" => type(121),
    mul2_3_4: "2*3*4" => type(24),

    div0_1: "0/1" => type(0),
    div12_1: "12/1" => type(12),
    div12_3: "12/3" => type(4),
    div11_11: "11/11" => type(1),
    div24_3_4: "24/3/4" => type(2),
    div1_2: "1/2" => type(BigRational::new(1.into(), 2.into())),
    div15_7: "15/7" => type(BigRational::new(15.into(), 7.into())),
    div45_3_7: "45/3/7" => type(BigRational::new(15.into(), 7.into())),

    div0_0: "0/0" => error(DivideByZero@1) type(error),
    div1_0: "1/0" => error(DivideByZero@1) type(error),

    muladd2_3_4: "2*3+4" => type(10),
    muladd2_3_4_neg: "-2*3+4" => type(-2),
    muladd2_3_4_pos: "+2*3+4" => type(10),

    addmul2_3_4: "2+3*4" => type(14),
    addmul2_3_4_neg: "-2+3*4" => type(10),
    addmul2_3_4_pos: "+2+3*4" => type(14),

    divadd2_3_4: "30/2*3" => type(45),
    divadd2_3_4_neg: "-30/2*3" => type(-45),
    divadd2_3_4_pos: "+30/2*3" => type(45),

    adddiv3_8_2: "3+8/2" => type(7),
    adddiv3_8_2_neg: "-3+8/2" => type(1),
    adddiv3_8_2_pos: "+3+8/2" => type(7),

    addsub0_0_0: "0+0-0" => type(0),
    addsub0_0_0_neg: "-0+0-0" => type(0),
    addsub0_0_0_pos: "+0+0-0" => type(0),
    addsub1_2_3: "1+2-3" => type(0),
    addsub1_2_3_neg: "-1+2-3" => type(-2),
    addsub1_2_3_pos: "+1+2-3" => type(0),

    subadd0_0_0: "0-0+0" => type(0),
    subadd0_0_0_neg: "-0-0+0" => type(0),
    subadd0_0_0_pos: "+0-0+0" => type(0),
    subadd1_2_3: "1-2+3" => type(2),
    subadd1_2_3_neg: "-1-2+3" => type(0),
    subadd1_2_3_pos: "+1-2+3" => type(2),

    addmul_missing_operator_precedence: "1 * + 3" => errors(MissingRightOperand@2) type(error),
    // muladd_missing_operator_precedence: "1 + * 3" => errors(MissingLeftOperand@4) type(error),
    addparen_missing_operator_precedence: "(1 + )" => errors(MissingRightOperand@3) type(error),
    parenadd_missing_operator_precedence: "( + 1)" => errors(MissingLeftOperand@2) type(error),

    neg_0: "-0" => type(0),
    neg_1: "-1" => type(-1),
    pos_0: "+0" => type(0),
    pos_1: "+1" => type(1),

    plusneg_5_2: "5 + -2" => type(3),
    timesneg_5_2: "5 * -2" => type(-10),

    trailing_neg: "0-" => error(UnrecognizedOperator@1) type(error),
    trailing_pos: "0+" => error(UnrecognizedOperator@1) type(error),
    sub_only:      "-" => errors(MissingLeftOperand@0,MissingRightOperand@0) type(error),
    add_only:      "+" => errors(MissingLeftOperand@0,MissingRightOperand@0) type(error),
    plus_minus: "1+-2" => error(UnrecognizedOperator@[1-2]) type(error),

    // + errors
    add_true_1: "true+1" => errors(BadTypeLeftOperand@4) type(error),
    add_1_true: "1+true" => errors(BadTypeRightOperand@1) type(error),
    add_false_1: "false+1" => errors(BadTypeLeftOperand@5) type(error),
    add_1_false: "1+false" => errors(BadTypeRightOperand@1) type(error),
    add_nothing_1: "()+1" => errors(BadTypeLeftOperand@2) type(error),
    add_1_nothing: "1+()" => errors(BadTypeRightOperand@1) type(error),
    add_error_1: "1/0+1" => errors(DivideByZero@1) type(error),
    add_1_error: "1+1/0" => errors(DivideByZero@3) type(error),

    add_true_true: "true+true" => errors(BadTypeLeftOperand@4,BadTypeRightOperand@4) type(error),
    add_false_true: "false+true" => errors(BadTypeLeftOperand@5,BadTypeRightOperand@5) type(error),
    add_true_false: "true+false" => errors(BadTypeLeftOperand@4,BadTypeRightOperand@4) type(error),
    add_false_false: "false+false" => errors(BadTypeLeftOperand@5,BadTypeRightOperand@5) type(error),
    add_true_error: "true+1/0" => errors(DivideByZero@6) type(error),
    add_error_true: "1/0+true" => errors(DivideByZero@1) type(error),
    add_false_error: "false+1/0" => errors(DivideByZero@7) type(error),
    add_error_false: "1/0+false" => errors(DivideByZero@1) type(error),
    add_true_nothing: "true+()" => errors(BadTypeLeftOperand@4,BadTypeRightOperand@4) type(error),
    add_nothing_true: "()+true" => errors(BadTypeLeftOperand@2,BadTypeRightOperand@2) type(error),
    add_false_nothing: "false+()" => errors(BadTypeLeftOperand@5,BadTypeRightOperand@5) type(error),
    add_nothing_false: "()+false" => errors(BadTypeLeftOperand@2,BadTypeRightOperand@2) type(error),

    add_error_error: "1/0+1/0" => errors(DivideByZero@1,DivideByZero@5) type(error),
    add_error_nothing: "1/0+()" => errors(DivideByZero@1) type(error),
    add_nothing_error: "()+1/0" => errors(DivideByZero@4) type(error),
    add_nothing_nothing: "()+()" => errors(BadTypeLeftOperand@2,BadTypeRightOperand@2) type(error),

    // - errors
    sub_true_1: "true-1" => errors(BadTypeLeftOperand@4) type(error),
    sub_1_true: "1-true" => errors(BadTypeRightOperand@1) type(error),
    sub_false_1: "false-1" => errors(BadTypeLeftOperand@5) type(error),
    sub_1_false: "1-false" => errors(BadTypeRightOperand@1) type(error),
    sub_nothing_1: "()-1" => errors(BadTypeLeftOperand@2) type(error),
    sub_1_nothing: "1-()" => errors(BadTypeRightOperand@1) type(error),
    sub_error_1: "1/0-1" => errors(DivideByZero@1) type(error),
    sub_1_error: "1-1/0" => errors(DivideByZero@3) type(error),

    sub_true_true: "true-true" => errors(BadTypeLeftOperand@4,BadTypeRightOperand@4) type(error),
    sub_false_true: "false-true" => errors(BadTypeLeftOperand@5,BadTypeRightOperand@5) type(error),
    sub_true_false: "true-false" => errors(BadTypeLeftOperand@4,BadTypeRightOperand@4) type(error),
    sub_false_false: "false-false" => errors(BadTypeLeftOperand@5,BadTypeRightOperand@5) type(error),
    sub_true_error: "true-1/0" => errors(DivideByZero@6) type(error),
    sub_error_true: "1/0-true" => errors(DivideByZero@1) type(error),
    sub_false_error: "false-1/0" => errors(DivideByZero@7) type(error),
    sub_error_false: "1/0-false" => errors(DivideByZero@1) type(error),
    sub_true_nothing: "true-()" => errors(BadTypeLeftOperand@4,BadTypeRightOperand@4) type(error),
    sub_nothing_true: "()-true" => errors(BadTypeLeftOperand@2,BadTypeRightOperand@2) type(error),
    sub_false_nothing: "false-()" => errors(BadTypeLeftOperand@5,BadTypeRightOperand@5) type(error),
    sub_nothing_false: "()-false" => errors(BadTypeLeftOperand@2,BadTypeRightOperand@2) type(error),

    sub_error_error: "1/0-1/0" => errors(DivideByZero@1,DivideByZero@5) type(error),
    sub_error_nothing: "1/0-()" => errors(DivideByZero@1) type(error),
    sub_nothing_error: "()-1/0" => errors(DivideByZero@4) type(error),
    sub_nothing_nothing: "()-()" => errors(BadTypeLeftOperand@2,BadTypeRightOperand@2) type(error),


    // * errors
    mul_true_1: "true*1" => errors(BadTypeLeftOperand@4) type(error),
    mul_1_true: "1*true" => errors(BadTypeRightOperand@1) type(error),
    mul_false_1: "false*1" => errors(BadTypeLeftOperand@5) type(error),
    mul_1_false: "1*false" => errors(BadTypeRightOperand@1) type(error),
    mul_nothing_1: "()*1" => errors(BadTypeLeftOperand@2) type(error),
    mul_1_nothing: "1*()" => errors(BadTypeRightOperand@1) type(error),
    mul_error_1: "(1/0)*1" => errors(DivideByZero@2) type(error),
    mul_1_error: "1*(1/0)" => errors(DivideByZero@4) type(error),

    mul_true_true: "true*true" => errors(BadTypeLeftOperand@4,BadTypeRightOperand@4) type(error),
    mul_false_true: "false*true" => errors(BadTypeLeftOperand@5,BadTypeRightOperand@5) type(error),
    mul_true_false: "true*false" => errors(BadTypeLeftOperand@4,BadTypeRightOperand@4) type(error),
    mul_false_false: "false*false" => errors(BadTypeLeftOperand@5,BadTypeRightOperand@5) type(error),
    mul_true_error: "true*(1/0)" => errors(DivideByZero@7) type(error),
    mul_error_true: "(1/0)*true" => errors(DivideByZero@2) type(error),
    mul_false_error: "false*(1/0)" => errors(DivideByZero@8) type(error),
    mul_error_false: "(1/0)*false" => errors(DivideByZero@2) type(error),
    mul_true_nothing: "true*()" => errors(BadTypeLeftOperand@4,BadTypeRightOperand@4) type(error),
    mul_nothing_true: "()*true" => errors(BadTypeLeftOperand@2,BadTypeRightOperand@2) type(error),
    mul_false_nothing: "false*()" => errors(BadTypeLeftOperand@5,BadTypeRightOperand@5) type(error),
    mul_nothing_false: "()*false" => errors(BadTypeLeftOperand@2,BadTypeRightOperand@2) type(error),

    mul_error_error: "(1/0)*(1/0)" => errors(DivideByZero@2,DivideByZero@8) type(error),
    mul_error_nothing: "(1/0)*()" => errors(DivideByZero@2) type(error),
    mul_nothing_error: "()*(1/0)" => errors(DivideByZero@5) type(error),
    mul_nothing_nothing: "()*()" => errors(BadTypeLeftOperand@2,BadTypeRightOperand@2) type(error),

    // / errors
    div_true_1: "true/1" => errors(BadTypeLeftOperand@4) type(error),
    div_1_true: "1/true" => errors(BadTypeRightOperand@1) type(error),
    div_false_1: "false/1" => errors(BadTypeLeftOperand@5) type(error),
    div_1_false: "1/false" => errors(BadTypeRightOperand@1) type(error),
    div_nothing_1: "()/1" => errors(BadTypeLeftOperand@2) type(error),
    div_1_nothing: "1/()" => errors(BadTypeRightOperand@1) type(error),
    div_error_1: "(1/0)/1" => errors(DivideByZero@2) type(error),
    div_1_error: "1/(1/0)" => errors(DivideByZero@4) type(error),

    div_true_true: "true/true" => errors(BadTypeLeftOperand@4,BadTypeRightOperand@4) type(error),
    div_false_true: "false/true" => errors(BadTypeLeftOperand@5,BadTypeRightOperand@5) type(error),
    div_true_false: "true/false" => errors(BadTypeLeftOperand@4,BadTypeRightOperand@4) type(error),
    div_false_false: "false/false" => errors(BadTypeLeftOperand@5,BadTypeRightOperand@5) type(error),
    div_true_error: "true/(1/0)" => errors(DivideByZero@7) type(error),
    div_error_true: "(1/0)/true" => errors(DivideByZero@2) type(error),
    div_false_error: "false/(1/0)" => errors(DivideByZero@8) type(error),
    div_error_false: "(1/0)/false" => errors(DivideByZero@2) type(error),
    div_true_nothing: "true/()" => errors(BadTypeLeftOperand@4,BadTypeRightOperand@4) type(error),
    div_nothing_true: "()/true" => errors(BadTypeLeftOperand@2,BadTypeRightOperand@2) type(error),
    div_false_nothing: "false/()" => errors(BadTypeLeftOperand@5,BadTypeRightOperand@5) type(error),
    div_nothing_false: "()/false" => errors(BadTypeLeftOperand@2,BadTypeRightOperand@2) type(error),

    div_error_error: "(1/0)/(1/0)" => errors(DivideByZero@2,DivideByZero@8) type(error),
    div_error_nothing: "(1/0)/()" => errors(DivideByZero@2) type(error),
    div_nothing_error: "()/(1/0)" => errors(DivideByZero@5) type(error),
    div_nothing_nothing: "()/()" => errors(BadTypeLeftOperand@2,BadTypeRightOperand@2) type(error),

    // Negative - errors
    neg_true: "-true" => errors(BadTypeRightOperand@0) type(error),
    neg_false: "-false" => errors(BadTypeRightOperand@0) type(error),
    neg_nothing: "-()" => errors(BadTypeRightOperand@0) type(error),
    neg_error: "-(1/0)" => errors(DivideByZero@3) type(error),

    // Positive + errors
    pos_true: "+true" => errors(BadTypeRightOperand@0) type(error),
    pos_false: "+false" => errors(BadTypeRightOperand@0) type(error),
    pos_nothing: "+()" => errors(BadTypeRightOperand@0) type(error),
    pos_error: "+(1/0)" => errors(DivideByZero@3) type(error),
}
