[package]
name = "berg-parser"
version = "0.1.0"
authors = ["John Keiser <john@johnkeiser.com>"]
edition = "2024"

[dependencies]
clippy = {version = "*", optional = true}
berg-util = {path = "../berg-util"}
string-interner = "*"

[dev-dependencies]
clippy = {version = "*"}
