[package]
name = "berg-compiler"
version = "0.1.0"
authors = ["John Keiser <john@johnkeiser.com>"]
edition = "2021"

[dependencies]
num = "*"
fnv = "*"
clippy = {version = "*", optional = true}
string-interner = "*"
matches = "*"

[dev-dependencies]
clippy = {version = "*"}
