[package]
name = "berg-compiler"
version = "0.1.0"
authors = ["John Keiser <john@johnkeiser.com>"]
edition = "2018"

[dependencies]
num = "0.1"
fnv = "1"
clippy = {version = "*", optional = true}

[dev-dependencies]
clippy = {version = "*"}
