[package]
name = "berg-util"
version = "0.1.0"
authors = ["John Keiser <john@johnkeiser.com>"]
edition = "2024"

[dependencies]
clippy = {version = "*", optional = true}

[dev-dependencies]
clippy = {version = "*"}
